.script:
  script:
    - |
      julia --project=@. -e '
        using Pkg
        Pkg.add([
          PackageSpec(name="SemialgebraicSets", rev="master"),
          PackageSpec(name="MultivariateMoments", rev="master"),
          PackageSpec(name="MultivariatePolynomials", rev="master"),
          PackageSpec(name="TypedPolynomials", rev="master"),
        ])
        Pkg.build()
        Pkg.test(coverage=true)'
.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'
Julia 1.6:
  image: julia:1.6
  extends:
    - .script
    - .coverage
Julia 1.8:
  image: julia:1.8
  extends:
    - .script
    - .coverage
pages:
  image: julia:1.6
  stage: deploy
  script:
    - |
      julia --project=docs -e '
        using Pkg
        Pkg.add([
          PackageSpec(name="SemialgebraicSets", rev="master"),
          PackageSpec(name="MultivariateMoments", rev="master"),
          PackageSpec(name="MultivariatePolynomials", rev="master"),
          PackageSpec(name="TypedPolynomials", rev="master"),
          PackageSpec(path=pwd()),
        ])
        Pkg.instantiate()
        using Documenter: doctest
        using Macaulay
        doctest(Macaulay)
        include("docs/make.jl")'
    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - main
