name = "CriticalValuePolynomial"
uuid = "bcb046b7-f005-4e9a-a986-fb3acd014398"
authors = ["Benoît Legat <benoit.legat@gmail.com>"]
version = "0.1.0"

[deps]
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
